### ISSUE TITLE
Surface mining

### ISSUE THREAD

**Issue by thomas-illiet** [jiri-otoupal/DualUniverse-Miner#1]
Hello guy,

Your miner can mine rock on planet?

![image](https://user-images.githubusercontent.com/2133666/197363902-8f50da60-f5e3-4021-af0f-57532aca8e6c.png)

Kind regards

**Comment by jiri-otoupal** [comment]
Hi Thomas,

Unfortunately this miner got outdated since the update that removed the ore from underground.
And currently I don't have a motivation to make it work for rocks. 
But it should be easier than making it for ores like back then, since there are strong differences that would make it possible even without ML.

**Comment by thomas-illiet** [comment]
I will keep an eye on you, if the motivation returns.
Thx :)
